Milestone 5: Styling
ioilmio/bookstore-cms pull request #6
Opened 2021-02-10 23:02 UTC by ioilmio

This milestone is about styling the bookstore using the provided design:
sass

2021-02-13 00:32 UTC, uche-inyama requested changes
## Changes Required

### Hi @ioilmio :wave: 

Your design is looking good. But you have left a handful of commented lines of code in your .scss files.

I have highlighted a few in the inline comments. Below are the list of files with one line comments:

*    nav.scss, line 52.
*    form.scss, line 20.
*    _config.scss, line 12.

Remove these comments from your codebase, then submit another form for a code review.

### Have a great day :slightly_smiling_face: 

#### Happy coding :man_technologist: 

#### ``` Uchechukwu Henry Inyama ```

2021-02-13 00:32 UTC, uche-inyama commented on src/styles/scss/book.scss
> +    // line-height: inherit;
#### Remove these commented lines of code.

2021-02-13 00:32 UTC, uche-inyama commented on src/styles/scss/booklist.scss
> +  // width: 80%;
#### To make your codebase neat, remove these lines of code.

2021-02-13 00:32 UTC, uche-inyama commented on src/styles/scss/nav.scss
> +    // }
#### Removed these commented lines of code.

2021-02-14 22:46 UTC, addod19 approved these changes
## Status: Approved :trophy: :balloon: 

Hi @ioilmio, great job on this project :+1: Having removed all the commented code in our files :smile: I hereby approved the project:+1: 

[Optional]
- The README file must include instructions about how to clone and run the project, tools or languages for the project, a live version, social handles of the author, etc

Kindly go ahead and merge into development and continue with your next projects :slightly_smiling_face: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

2021-02-17 16:11 UTC, merged